# Generated by Django 3.2.7 on 2021-09-12 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210911_1812'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='advanceduser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Статус администратора'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Статус суперпользователя'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Последнее посещение'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='advanceduser',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
