# Generated by Django 3.2.7 on 2021-09-12 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUserFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.BooleanField(default=False, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Компания пользователя',
                'verbose_name_plural': 'Компании пользователья',
                'ordering': ['firm'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='corporations.firm', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporations.profession', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=phone_field.models.PhoneField(help_text='Телефонный номер', max_length=31, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='profession',
            field=models.CharField(max_length=150, unique=True, verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='UserFirm',
        ),
        migrations.AddField(
            model_name='superuserfirm',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporations.firm', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='superuserfirm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
