# Generated by Django 3.2.7 on 2021-09-12 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporations', '0002_auto_20210912_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFirmRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Пользователь с правами администратора',
                'verbose_name_plural': 'Пользователи с правами администратора',
                'ordering': ['firm'],
            },
        ),
        migrations.AddField(
            model_name='firm',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель компании в базе'),
        ),
        migrations.DeleteModel(
            name='SuperUserFirm',
        ),
        migrations.AddField(
            model_name='userfirmrelation',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corporations.firm', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='userfirmrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='firm',
            name='access_edit',
            field=models.ManyToManyField(through='corporations.UserFirmRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userfirmrelation',
            constraint=models.UniqueConstraint(fields=('user', 'firm'), name='unique_userfirm'),
        ),
    ]
